version: '3.7'

services:
  girouette:
    build:
      context: .
      dockerfile: ./Dockerfile.devel
    container_name: girouette
    restart: always
    dns_search:
      - 1.1.1.1
    ports:
      - 443:443
      - 80:80
      - 53:5353
      - 53:5353/udp
    environment:
      NODE_ENV: development
      TLDS: '.devel'
    volumes:
      - './app:/app'
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      girouette.domains: girouette.devel:8080
      girouette.group: Girouette

  www:
    tty: true
    image: node:latest
    command: sh -c "cd /app && npm run start"
    restart: always
    working_dir: /app
    volumes:
      - './front:/app'
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
      HOST: 0.0.0.0
      PORT: 3000
    networks:
      - girouette
      - traefik
      - webgateway
    labels:
      traefik.frontend.rule: 'Host:girouettedev.devel'
      traefik.port: 3000
      girouette.group: Girouette

  whoami:
    image: emilevauge/whoami
    networks:
      - girouette
    restart: always
    labels:
      girouette.domains: whoami.devel:80
      girouette.group: Girouette

networks:
  traefik:
    external:
      name: traefik
  girouette:
    external:
      name: girouette
  webgateway:
    external:
      name: traefikforwebdev_webgateway
