version: '3.7'

services:
  girouette:
    build:
      context: .
      dockerfile: ./Dockerfile.devel
    restart: always
    networks:
      - girouette
      - traefik
      - webgateway
    dns_search:
      - 1.1.1.1
    ports:
      - 443:443
      - 80:80
      - 53:5353
      - 53:5353/udp
    volumes:
      - './app:/app'
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      traefik.frontend.rule: 'Host:girouette.devel'
      traefik.port: 8080

  www:
    tty: true
    image: node:latest
    command: sh -c "cd /app && npm run start"
    restart: always
    working_dir: /app
    volumes:
      - './front:/app'
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
    networks:
      - girouette
      - traefik
      - webgateway
    labels:
      traefik.frontend.rule: 'Host:girouettedev.devel'
      traefik.port: 3000

  whoami:
    image: emilevauge/whoami
    networks:
      - girouette
      - traefik
      - webgateway
    restart: always
    labels:
      girouette_domain: whoami.devel
      girouette_port: 80
      traefik.frontend.rule: 'Host:whoami.devel'
      traefik.port: 80

networks:
  traefik:
    external:
      name: traefik
  girouette:
    external:
      name: girouette
  webgateway:
    external:
      name: traefikforwebdev_webgateway
