version: "3.7"

services:
  girouette:
    build:
      context: .
      dockerfile: ./Dockerfile.devel
    container_name: girouette
    restart: always
    dns_search:
      - 1.1.1.1
    ports:
      - 443:443
      - 80:80
      - 53:5353
      - 53:5353/udp
    networks:
      - girouette
    environment:
      NODE_ENV: development
      TLDS: ".devel"
      DNSMASQ: "address=/.devel/127.0.0.1"
      TLD: ".devel"
      DNS: "1.1.1.1"
    volumes:
      - "./app:/app"
      - "./front:/front"
      - "girouette:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      girouette.domains: girouette.devel:8080
      girouette.group: Girouette

  www:
    tty: true
    image: node:16
    command: sh -c "cd /app && npm run dev"
    restart: always
    working_dir: /app
    volumes:
      - "./front:/app"
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
    networks:
      - girouette
    labels:
      traefik.frontend.rule: "Host:girouettedev.devel"
      traefik.port: 3000
      girouette.group: Girouette

  whoami:
    image: emilevauge/whoami
    networks:
      - girouette
    restart: always
    labels:
      girouette.domains: whoami.devel:80
      girouette.group: Girouette

volumes:
  girouette:
    external:
      name: girouette

networks:
  girouette:
    external:
      name: girouette
