version: '3.7'

services:
  girouette:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - girouette
      - traefik
      - webgateway
    ports:
      - 443:443
      - 80:80
    volumes:
      - './app:/app'
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      girouette.domains: girouette.devel:8080

  whoami:
    image: emilevauge/whoami
    networks:
      - girouette
      - traefik
      - webgateway
    restart: always
    labels:
      girouette_domain: whoami.devel
      girouette_port: 80
      traefik.frontend.rule: 'Host:whoami.devel'
      traefik.port: 80

networks:
  traefik:
    external:
      name: traefik
  girouette:
    external:
      name: girouette
  webgateway:
    external:
      name: traefikforwebdev_webgateway
